apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedServiceAccount
metadata:
  name: test-serviceaccount
spec:
  template:
    automountServiceAccountToken: true
  placement:
    clusters:
    - name: cluster2
    - name: cluster1
